// const Endpoints = {
// 	seeker: "https://pet-pal-web-backend-alligators.vercel.app/seeker/",
// 	seekers: "https://pet-pal-web-backend-alligators.vercel.app/seekers/",
// 	shelter: "https://pet-pal-web-backend-alligators.vercel.app/shelter/",
// 	shelters: "https://pet-pal-web-backend-alligators.vercel.app/shelters/",
// 	shelterlists: "https://pet-pal-web-backend-alligators.vercel.app/shelterlists/",
// 	token: "https://pet-pal-web-backend-alligators.vercel.app/api/token/",
// 	search: "https://pet-pal-web-backend-alligators.vercel.app/pets/results/",
// 	pet: "https://pet-pal-web-backend-alligators.vercel.app/pets/:pk/",
// 	application: "https://pet-pal-web-backend-alligators.vercel.app/applications/",
// 	applicationfilled: "https://pet-pal-web-backend-alligators.vercel.app/applications/:pk/",
// 	applicationcomments: "https://pet-pal-web-backend-alligators.vercel.app/applications/:pk/comment/",
// 	updateshelter: "https://pet-pal-web-backend-alligators.vercel.app/shelter/:pk/",
// 	updateseeker: "https://pet-pal-web-backend-alligators.vercel.app/seeker/:pk/",
// 	pets: "https://pet-pal-web-backend-alligators.vercel.app/pets/",
// 	specificshelter: "https://pet-pal-web-backend-alligators.vercel.app/shelter/:pk/",
// 	specificseeker: "https://pet-pal-web-backend-alligators.vercel.app/seeker/:pk/",
// 	petresults: "https://pet-pal-web-backend-alligators.vercel.app/pets/results/",
// 	applications: "https://pet-pal-web-backend-alligators.vercel.app/applications/",
// 	notifs: "https://pet-pal-web-backend-alligators.vercel.app/notifications/",
// 	sheltercomments: "https://pet-pal-web-backend-alligators.vercel.app/shelter/:pk/comment/",
// 	specificpet: "https://pet-pal-web-backend-alligators.vercel.app/pets/:pk/",
// 	google: `https://pet-pal-web-backend-alligators.vercel.app/google/`,
// }

// local testing
const Endpoints = {
	seeker: "http://localhost:80/seeker/",
	seekers: "http://localhost:80/seekers/",
	shelter: "http://localhost:80/shelter/",
	shelters: "http://localhost:80/shelters/",
	shelterlists: "http://localhost:80/shelterlists/",
	token: "http://localhost:80/api/token/",
	search: "http://localhost:80/pets/results/",
	pet: "http://localhost:80/pets/:pk/",
	application: "http://localhost:80/applications/",
	applicationfilled: "http://localhost:80/applications/:pk/",
	applicationcomments: "http://localhost:80/applications/:pk/comment/",
	updateshelter: "http://localhost:80/shelter/:pk/",
	updateseeker: "http://localhost:80/seeker/:pk/",
	pets: "http://localhost:80/pets/",
	specificshelter: "http://localhost:80/shelter/:pk/",
	specificseeker: "http://localhost:80/seeker/:pk/",
	petresults: "http://localhost:80/pets/results/",
	applications: "http://localhost:80/applications/",
	notifs: "http://localhost:80/notifications/",
	sheltercomments: "http://localhost:80/shelter/:pk/comment/",
	specificpet: "http://localhost:80/pets/:pk/",
	google: `http://localhost:80/google/`,
}

export default Endpoints