# Generated by Django 4.2.7 on 2023-12-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='medical_history',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pet',
            name='others',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pet',
            name='personality',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pet',
            name='special_needs',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
