# Generated by Django 4.2.7 on 2023-12-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seeker',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='photo',
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
